FROM postgres:18-alpine

RUN apk add --no-cache git build-base \
    && cd /tmp \
    && git clone --depth 1 https://github.com/pgvector/pgvector.git \
    && cd pgvector \
    && make \
    && make install \
    && rm -rf /tmp/pgvector \
    && apk del git build-base
